#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

# register your commands here
$application->add(new Commands\Hello());

$application->run();

